# Generated by Django 5.0.6 on 2024-05-12 17:02

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('expense_for', models.CharField(choices=[('salary', 'PAYROLL'), ('rent', 'RENT'), ('labour', 'LABOR'), ('material', 'MATERIAL'), ('travel', 'TRAVEL'), ('marketing', 'MARKETING'), ('loan', 'LOAN'), ('others', 'OTHERS')], max_length=100)),
                ('mode', models.CharField(choices=[('cash', 'CASH'), ('online', 'ONLINE')], max_length=8, null=True)),
                ('expense_reference_code', models.CharField(blank=True, help_text='Please provide reference number for online expense.', max_length=100, null=True)),
                ('expense_date', models.DateField()),
                ('details', models.CharField(help_text='Please add details for future auditing purpose', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_no', models.CharField(max_length=255, unique=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='students_picture')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('section', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=5, verbose_name='Class')),
                ('mobile_no', models.CharField(max_length=10)),
                ('academic_session', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=10)),
                ('identity_card_issued', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('admission_date', models.DateField()),
                ('village', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=255, unique=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='teachers_picture')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(help_text='Example: English Teacher', max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.FloatField(help_text='Employee work experience in years in time of joining', max_length=2)),
                ('mobile_no', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('relieving_date', models.DateField(blank=True, help_text='Provide this date if employee is leaving from organization', null=True)),
                ('identity_card_issued', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('income', 'INCOME'), ('expense', 'EXPENSE')], max_length=10)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(choices=[('cash', 'CASH'), ('online', 'ONLINE')], max_length=8, null=True)),
                ('debit', models.PositiveIntegerField(default=0)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('closing', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee_paid', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tuition_fee_due', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('admission_fee_paid', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('admission_fee_due', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('learning_material_fee_paid', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('learning_material_fee_due', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('others_fee_paid', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('others_fee_due', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('mode', models.CharField(choices=[('cash', 'CASH'), ('online', 'ONLINE')], max_length=8, null=True)),
                ('payment_reference_code', models.CharField(blank=True, help_text='Please provide reference number for online payment.', max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='Please add note for future auditing purpose')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
