# Generated by Django 5.0.4 on 2024-04-25 15:57

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=6)),
                ('expense_for', models.CharField(choices=[('salary', 'PAYROLL'), ('rent', 'RENT'), ('labour', 'LABOR'), ('material', 'MATERIAL'), ('travel', 'TRAVEL'), ('marketing', 'MARKETING'), ('loan', 'LOAN')], max_length=100)),
                ('expense_date', models.DateField()),
                ('details', models.CharField(help_text='Please add details for future auditing purpose', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_no', models.CharField(max_length=255, unique=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='students_picture')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('section', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=5)),
                ('mobile_no', models.CharField(max_length=10)),
                ('academic_session', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=10)),
                ('admission_date', models.DateField()),
                ('village', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.FloatField(max_length=6)),
                ('paid', models.FloatField(max_length=6)),
                ('payment_date', models.DateField()),
                ('payment_for', models.CharField(choices=[('tuition_fee', 'TUITION FEE'), ('admission_fee', 'ADMISSION FEE'), ('learning_material_fee', 'LEARNING MATERIAL FEE'), ('uniform_fee', 'UNIFORM FEE'), ('hostel_fee', 'HOSTEL FEE'), ('transport_fee', 'TRANSPORT FEE'), ('food_fee', 'FOOD FEE'), ('other_fee', 'OTHER FEE')], max_length=100, null=True)),
                ('mode', models.CharField(choices=[('cash', 'CASH'), ('online', 'ONLINE')], max_length=8, null=True)),
                ('payment_reference_code', models.CharField(blank=True, help_text='Please provide reference number for online payment.', max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='Please add note for future auditing purpose')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
