# Generated by Django 5.0.6 on 2024-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='hostel_fee_due',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='hostel_fee_paid',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
