# Generated by Django 5.0.6 on 2024-05-20 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_studentpayment_hostel_fee_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
