# Generated by Django 5.0.6 on 2024-05-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentpayment_hostel_fee_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='admission_fee_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='hostel_fee_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='learning_material_fee_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='others_fee_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='tuition_fee_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
