# Generated by Django 5.0.4 on 2024-04-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_identity_card_issued_alter_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('income', 'INCOME'), ('expense', 'EXPENSE')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='mode',
            field=models.CharField(choices=[('cash', 'CASH'), ('online', 'ONLINE')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_for',
            field=models.CharField(choices=[('salary', 'PAYROLL'), ('rent', 'RENT'), ('labour', 'LABOR'), ('material', 'MATERIAL'), ('travel', 'TRAVEL'), ('marketing', 'MARKETING'), ('loan', 'LOAN'), ('others', 'OTHERS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='payment_for',
            field=models.CharField(choices=[('tuition_fee', 'TUITION FEE'), ('admission_fee', 'ADMISSION FEE'), ('learning_material_fee', 'LEARNING MATERIAL FEE'), ('uniform_fee', 'UNIFORM FEE'), ('hostel_fee', 'HOSTEL FEE'), ('transport_fee', 'TRANSPORT FEE'), ('food_fee', 'FOOD FEE'), ('others', 'OTHERS FEE')], max_length=100, null=True),
        ),
    ]
