# Generated by Django 5.0.4 on 2024-04-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_balancesheet_expense_mode_alter_expense_expense_for_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalanceSheet',
            new_name='Transaction',
        ),
    ]
