# Generated by Django 5.0.4 on 2024-05-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
