# Generated by Django 5.0.4 on 2024-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_reference_code',
            field=models.CharField(blank=True, help_text='Please provide reference number for online expense.', max_length=100, null=True),
        ),
    ]
