# Generated by Django 5.0.4 on 2024-05-07 07:37

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expense_expense_reference_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=255, unique=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='teachers_picture')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(help_text='Example: English Teacher', max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.FloatField(help_text='Employee work experience in years in time of joining', max_length=2)),
                ('mobile_no', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('relieving_date', models.DateField(blank=True, help_text='Provide this date if employee is leaving from organization', null=True)),
                ('identity_card_issued', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('permanent_address', models.TextField()),
            ],
        ),
    ]
