# Generated by Django 5.0.4 on 2024-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='due',
            field=models.PositiveIntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='paid',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
