# Generated by Django 5.0.4 on 2024-05-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_expense_amount_alter_studentpayment_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='due',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='paid',
            field=models.PositiveIntegerField(),
        ),
    ]
