# Generated by Django 5.0.4 on 2024-05-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paymentcategory_remove_studentpayment_payment_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='closing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
