# Generated by Django 5.0.4 on 2024-05-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction_closing_transaction_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('cash', 'CASH'), ('online', 'ONLINE')], max_length=8, null=True),
        ),
    ]
