# Generated by Django 5.0.4 on 2024-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_transaction_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='closing',
            field=models.IntegerField(default=0),
        ),
    ]
