# Generated by Django 5.0.6 on 2024-05-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_transaction_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
