# Generated by Django 5.0.6 on 2024-05-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_transaction_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for', models.CharField(max_length=255)),
                ('paid', models.PositiveIntegerField()),
                ('due', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentpayment')),
            ],
        ),
    ]
