# Generated by Django 5.0.6 on 2024-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_studentpaymentitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='payment_for',
        ),
        migrations.RemoveField(
            model_name='studentpaymentitems',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='due',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='paid',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='admission_fee_due',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='admission_fee_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='learning_material_fee_due',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='learning_material_fee_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='others_fee_due',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='others_fee_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='tuition_fee_due',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='tuition_fee_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PaymentCategory',
        ),
        migrations.DeleteModel(
            name='StudentPaymentItems',
        ),
    ]
