# Generated by Django 5.0.6 on 2024-05-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_studentpayment_payment_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='admission_fee_due',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='admission_fee_paid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='learning_material_fee_due',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='learning_material_fee_paid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='others_fee_due',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='others_fee_paid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='tuition_fee_due',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='tuition_fee_paid',
            field=models.PositiveIntegerField(),
        ),
    ]
