# Generated by Django 5.0.6 on 2024-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_studentpayment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='admission_fee_due',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='admission_fee_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='learning_material_fee_due',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='learning_material_fee_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='others_fee_due',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='others_fee_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='tuition_fee_due',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='tuition_fee_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
